name: Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [self-hosted, linux, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
    - name: Build
      run: CGO_ENABLED=0 go build -v -o shutters-api
    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: shutters-api
        path: shutters-api
