name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/arm64'
          package: ''
          compress: 'false'
          name: 'shutters-api'
          dest: 'build'
    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: shutters-api
        path: build/shutters-api-linux-arm64
